### ISSUE TITLE
Due to data type issue composer2_airflow_rest_api is not hitting the DAG

### ISSUE THREAD

**Issue by subhajitkp007** [subhajitkp007/cloud_function_trigger_DAG#1]
# ISSUE reproduce steps

- follow the instruction as https://cloud.google.com/composer/docs/composer-2/triggering-with-gcf and deploy the dag and cloud function
-  Once deployed successfully try to trigger it from the test option of cloud function 
- or use cloud shell and trigger the cloud function 
` curl -X POST cloudfunction_https_url \
-H "Authorization:bearer $(gcloud auth print-identity-token)" \
-H "Content-Type:application/json" \
-d '{"test":"test"}'`

- find below the error logs

``` Exception on / [POST] Traceback (most recent call last): File "/layers/google.python.pip/pip/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app response = self.full_dispatch_request() File "/layers/google.python.pip/pip/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request rv = self.handle_user_exception(e) File "/layers/google.python.pip/pip/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request rv = self.dispatch_request() File "/layers/google.python.pip/pip/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args) File "/layers/google.python.pip/pip/lib/python3.7/site-packages/functions_framework/__init__.py", line 99, in view_func return function(request._get_current_object()) File "/workspace/main.py", line 49, in trigger_dag_gcf composer2_airflow_rest_api.trigger_dag(web_server_url, dag_id, data) File "/workspace/composer2_airflow_rest_api.py", line 46, in trigger_dag data = jsonify(data) File "/layers/google.python.pip/pip/lib/python3.7/site-packages/flask/json/__init__.py", line 355, in jsonify f"{dumps(data, indent=indent, separators=separators)}\n", File "/layers/google.python.pip/pip/lib/python3.7/site-packages/flask/json/__init__.py", line 133, in dumps rv = _json.dumps(obj, **kwargs) File "/opt/python3.7/lib/python3.7/json/__init__.py", line 238, in dumps **kw).encode(obj) File "/opt/python3.7/lib/python3.7/json/encoder.py", line 199, in encode chunks = self.iterencode(o, _one_shot=True) File "/opt/python3.7/lib/python3.7/json/encoder.py", line 257, in iterencode return _iterencode(o, 0) File "/layers/google.python.pip/pip/lib/python3.7/site-packages/flask/json/__init__.py", line 57, in default return super().default(o) File "/opt/python3.7/lib/python3.7/json/encoder.py", line 179, in default raise TypeError(f'Object of type {o.__class__.__name__} ' TypeError: Object of type Request is not JSON serializable```

**Comment by subhajitkp007** [comment]
Fixed issue #1
